//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspSajt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class aktivnosti
    {
        public int id_aktivnosti { get; set; }
        public int id_korisnik { get; set; }
        public string mess { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual korisnik korisnik2 { get; set; }
    }
}
