//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspSajt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        public autor()
        {
            this.knjigas = new HashSet<knjiga>();
        }
    
        public int id_autor { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string biografija { get; set; }
    
        public virtual ICollection<knjiga> knjigas { get; set; }
    }
}
