//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspSajt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class knjiga
    {
        public knjiga()
        {
            this.cenas = new HashSet<cena>();
            this.komentars = new HashSet<komentar>();
            this.korpas = new HashSet<korpa>();
            this.zanrKnjigas = new HashSet<zanrKnjiga>();
        }
    
        public int id_knjiga { get; set; }
        public int id_autor { get; set; }
        public string naziv { get; set; }
        public string slika { get; set; }
        public string godina { get; set; }
        public string opis { get; set; }
        public string slikaMala { get; set; }
    
        public virtual ICollection<cena> cenas { get; set; }
        public virtual ICollection<komentar> komentars { get; set; }
        public virtual ICollection<korpa> korpas { get; set; }
        public virtual ICollection<zanrKnjiga> zanrKnjigas { get; set; }
        public virtual autor autor1 { get; set; }
    }
}
