//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspSajt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class meniuloga
    {
        public int id_meniuloga { get; set; }
        public Nullable<int> id_meni { get; set; }
        public string uloga { get; set; }
    
        public virtual meni meni1 { get; set; }
    }
}
